Repository openshift/cert-manager-operator, pull requests merged in 2022-12, with the labels that each got.

#86 Fix valid-subscription annotation in manifests/csv
  bundle/manifests/cert-manager.clusterserviceversion.yaml
Labels: lgtm, approved

#84 CFE-676: Feature/decouple cert manager operator as a clusteroperator
  pkg/controller/deployment/cert_manager_cainjector_deployment.go
  pkg/controller/deployment/cert_manager_controller_deployment.go
  pkg/controller/deployment/cert_manager_controller_set.go
  pkg/controller/deployment/cert_manager_webhook_deployment.go
  pkg/controller/deployment/generic_deployment_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#89 Changes to ClusterServiceVersion
  Makefile
  bundle.Dockerfile
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#85 CFE-668: Feature/generic deployment controller
  Makefile
  pkg/controller/deployment/cert_manager_cainjector_deployment.go
  pkg/controller/deployment/cert_manager_controller_deployment.go
  pkg/controller/deployment/cert_manager_controller_set.go
  pkg/controller/deployment/cert_manager_webhook_deployment.go
  pkg/controller/deployment/generic_deployment_controller.go
  pkg/operator/operatorclient/operatorclient.go
  vendor/github.com/openshift/library-go/pkg/apps/deployment/status.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/deploymentcontroller/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/deploymentcontroller/helpers.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, tide/merge-method-squash

#90 Fixes in ClusterServiceVersion manifest
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
  config/samples/kustomization.yaml
  config/samples/letsencrypt/cert-manager.io_v1_certificate.yaml
  config/samples/letsencrypt/cert-manager.io_v1_issuer.yaml
  config/samples/letsencrypt/extra/acme.cert-manager.io_v1_challenge.yaml
  config/samples/letsencrypt/extra/acme.cert-manager.io_v1_order.yaml
  config/samples/letsencrypt/extra/cert-manager.io_v1_certificaterequest.yaml
  config/samples/letsencrypt/extra/kustomization.yaml
  config/samples/letsencrypt/kustomization.yaml
  config/samples/operator.openshift.io_v1alpha1_certmanager.yaml
  config/samples/selfsigned/cert-manager.io_v1_certificate.yaml
  config/samples/selfsigned/cert-manager.io_v1_clusterissuer.yaml
  config/samples/selfsigned/cert-manager.io_v1_issuer.yaml
  config/samples/selfsigned/kustomization.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved
