Repository openshift/cert-manager-operator, pull requests merged in 2023-02, with the labels that each got.

#101 CFE-754: Add seccompProfile RuntimeDefault to operator deployment
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#93 CFE-740: Updated cert-manager-operator API to enable customization
  api/operator/v1alpha1/certmanager_types.go
  api/operator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.openshift.io_certmanagers.yaml
  config/crd/bases/operator.openshift.io_certmanagers.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#102 CFE-694: CSV changes for olm release channel, version, annotations
  Makefile
  bundle.Dockerfile
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#104 Add default channel as stable-v1
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#103 CFE-755: Support cluster-wide egress proxy injection
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
  docs/proxy.md
  go.mod
  go.sum
  pkg/cmd/operator/cmd.go
  pkg/controller/deployment/cert_manager_cainjector_deployment.go
  pkg/controller/deployment/cert_manager_controller_deployment.go
  pkg/controller/deployment/cert_manager_controller_set.go
  pkg/controller/deployment/cert_manager_webhook_deployment.go
  pkg/controller/deployment/deployment_overrides.go
  pkg/controller/deployment/generic_deployment_controller.go
  pkg/operator/starter.go
  vendor/github.com/operator-framework/operator-lib/LICENSE
  vendor/github.com/operator-framework/operator-lib/proxy/doc.go
  vendor/github.com/operator-framework/operator-lib/proxy/proxy.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#105 Use OpenShift subscription as 'OKE and up'
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#106 Update CertManager display name and description
  api/operator/v1alpha1/certmanager_types.go
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
  test/e2e/cert_manager_deployment_test.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, tide/merge-method-squash
