Repository openshift/cert-manager-operator, pull requests merged in 2023-05, with the labels that each got.

#122 OCPBUGS-9960: Add disable operand delete annotation
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, bugzilla/valid-bug, docs-approved, px-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#120 OCPBUGS-9998: Ambient credentials support
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  docs/cloud_credentials.md
  pkg/cmd/operator/cmd.go
  pkg/controller/deployment/cert_manager_cainjector_deployment.go
  pkg/controller/deployment/cert_manager_controller_deployment.go
  pkg/controller/deployment/cert_manager_controller_set.go
  pkg/controller/deployment/cert_manager_webhook_deployment.go
  pkg/controller/deployment/credentials_request.go
  pkg/controller/deployment/deployment_overrides.go
  pkg/controller/deployment/deployment_overrides_validation.go
  pkg/controller/deployment/generic_deployment_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1alpha1/insightsdatagather.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1alpha1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1alpha1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1alpha1/insightsdatagather.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, bugzilla/valid-bug, docs-approved, px-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#124 Change order of logLevel hook
  pkg/controller/deployment/generic_deployment_controller.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#125 OCPBUGS-9960: Add uninstall message annotation to csv
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, bugzilla/valid-bug, docs-approved, px-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#128 OCPBUGS-14129: Nil panic fix in validateLabels
  pkg/controller/deployment/deployment_overrides_validation.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference
