Repository openshift/cert-manager-operator, pull requests merged in 2023-10, with the labels that each got.

#146 OCPBUGS-19446: Remove nodeaffinity from rbac proxy patch
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#149 CM-201,CM-208: add CSV labels for non-amd64 architectures
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#157 CM-215: add nodeaffinity for non-x86 archs
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#158 Fix z-stream release channel to stable-v1.11
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#161 [cert-manager-1.11] Bump golang to 1.20
  .ci-operator.yaml
  Makefile
  go.mod
  images/ci/Dockerfile
Labels: lgtm, qe-approved, approved, docs-approved, px-approved
