Repository openshift/cert-manager-operator, pull requests merged in 2024-07, with the labels that each got.

#188 OCPBUGS-23406: Enable AllNamespaces install mode
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-bug, jira/valid-reference

#189 OCPBUGS-34698: Fix for TestCertRenew sporadic failures
  test/e2e/cert_manager_deployment_test.go
  test/e2e/testdata/acme/deployment.yaml
  test/e2e/utils_test.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-bug, jira/valid-reference

#179 CM-257: Add case to use Issuer with "--issuer-ambient-credentials" on AWS
  test/e2e/certificates_test.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#186 OCPBUGS-24193: Use `imagePullPolicy: IfNotPresent` for operator deployment
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-bug, jira/valid-reference

#170 MULTIARCH-3780: Added Test Case Modification for IBMCloud and Power
  test/e2e/certificates_test.go
  test/e2e/testdata/acme/certificate_ibmcis.yaml
  test/e2e/testdata/acme/clusterissuer_ibmcis.yaml
Labels: lgtm, qe-approved, approved, ok-to-test, docs-approved, px-approved, jira/valid-reference
