Repository openshift/cert-manager-operator, pull requests merged in 2024-10, with the labels that each got.

#207 CM-359: Remove konflux specific configs
  Dockerfile.konflux
  bundle.Dockerfile.konflux
  bundle/render_templates.sh
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#210 [cert-manager-1.15] CM-359 : Update operator CSV as required for the konflux
  .snyk
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: tide/merge-method-rebase, lgtm, qe-approved, approved, docs-approved, px-approved

#209 [cert-manager-1.14] CM-359 : Update operator CSV as required for the konflux
  .snyk
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#196 Updates the reviewers and approvers
  OWNERS
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#206 CM-409: Update replaces and skipRange to include 1.14.1
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#194 CM-261: utilize ginkgo label filter to differentiate cloud platforms
  Makefile
  go.mod
  go.sum
  test/e2e/certificates_test.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/CONTRIBUTING.md
  vendor/github.com/onsi/ginkgo/v2/Makefile
  vendor/github.com/onsi/ginkgo/v2/ginkgo/watch/package_hash.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  vendor/github.com/onsi/ginkgo/v2/table_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/label_filter.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference
