Repository openshift/cert-manager-operator, pull requests merged in 2025-04, with the labels that each got.

#257 CM-485: migrate Go testing e2e cases to Ginkgo framework
  test/e2e/cert_manager_deployment_test.go
  test/e2e/certificates_test.go
  test/e2e/overrides_test.go
  test/e2e/utils_test.go
  test/library/cert_utils.go
  test/library/utils.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#262 Rename typos in filename `deployment_helper_test.go`
  pkg/controller/deployment/deployment_helper_test.go
Labels: lgtm, qe-approved, approved, ok-to-test, docs-approved, px-approved

#264 Remove unnecessary .ObjectMeta
  pkg/controller/istiocsr/deployments.go
  pkg/controller/istiocsr/test_utils.go
  pkg/controller/istiocsr/utils.go
  test/e2e/certificates_test.go
  test/library/utils.go
Labels: lgtm, qe-approved, approved, ok-to-test, docs-approved, px-approved

#260 Use `k8s.io/utils/ptr` instead of deprecated `k8s.io/utils/pointer`
  pkg/controller/deployment/deployment_overrides.go
Labels: lgtm, qe-approved, approved, ok-to-test, docs-approved, px-approved

#267 Avoid e2e to pass with faulty status
  test/e2e/overrides_test.go
  test/e2e/utils_test.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved
