Repository openshift/cert-manager-operator, pull requests merged in 2025-02, with the labels that each got.

#230 fix: allow `make build` to run w/o strictfipsruntime (locally)
  Makefile
  hack/go-fips.sh
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#226 CM-423: Adds e2e test for istio-csr controller with grpc CreateCertificate call
  test/e2e/cert_manager_deployment_test.go
  test/e2e/certificates_test.go
  test/e2e/istio_csr_test.go
  test/e2e/testdata/istio/istio_ca_issuer.yaml
  test/e2e/testdata/istio/istio_csr.yaml
  test/e2e/utils_test.go
  test/library/utils.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#247 Refactor `test/e2e/testdata` to use go template based replacements
  test/e2e/certificates_test.go
  test/e2e/config_template.go
  test/e2e/testdata/acme/certificate_gcp.yaml
  test/e2e/testdata/acme/certificate_ibmcis.yaml
  test/e2e/testdata/acme/clusterissuer_gcp.yaml
  test/e2e/testdata/acme/clusterissuer_ibmcis.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#243 Implements rand deprecation by removing seed initializer
  main.go
Labels: lgtm, qe-approved, approved, ok-to-test, docs-approved, px-approved
