Repository openshift/cert-manager-operator, pull requests merged in 2025-05, with the labels that each got.

#265 Improves makefile to add check-tools target
  Makefile
Labels: lgtm, qe-approved, approved, ok-to-test, docs-approved, px-approved, tide/merge-method-squash

#271 CM-499: Enable disconnected support via annotation in operator CSV
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#272 Fix upstream version in CSV description
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#276 Update Makefile with channel stable-v1.16
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#274 Update min Kubernetes version in CSV
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, docs-approved, px-approved
