Repository openshift/cert-manager-operator, pull requests merged in 2025-06, with the labels that each got.

#277 CM-574: Enhance operand metrics doc based on latest builds
  docs/operand_metrics.md
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#279 CM-590: deliberately fail the e2e on encountering an unexpected Degraded condition
  test/e2e/certificates_test.go
  test/e2e/condition_matcher_test.go
  test/e2e/condition_matcher_unit_test.go
  test/e2e/istio_csr_test.go
  test/e2e/overrides_test.go
  test/e2e/suite_test.go
  test/e2e/utils_test.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference

#280 OCPBUGS-56758: Add tokenrequest RBAC for operator controller manager
  bundle/manifests/cert-manager-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  pkg/controller/deployment/certmanager_controller.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-bug, jira/valid-reference

#289 Update OWNERS
  OWNERS
  test/OWNERS
Labels: lgtm, qe-approved, approved, docs-approved, px-approved

#278 CM-561: Turn o/api `configv1.Infrastructure` into an optional dependency
  pkg/controller/deployment/cert_manager_cainjector_deployment.go
  pkg/controller/deployment/cert_manager_controller_deployment.go
  pkg/controller/deployment/cert_manager_controller_set.go
  pkg/controller/deployment/cert_manager_webhook_deployment.go
  pkg/controller/deployment/generic_deployment_controller.go
  pkg/operator/optionalinformer/optional_informer.go
  pkg/operator/optionalinformer/optional_informer_test.go
  pkg/operator/starter.go
Labels: lgtm, qe-approved, approved, docs-approved, px-approved, jira/valid-reference
